name: Build APK Assinado

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Restaurar keystore
        run: |
          echo "${{ secrets.GEOTRACK_KEYSTORE }}" | base64 --decode > geotrack-release.jks

      - name: Gerar APK
        run: gradle assembleRelease

      - name: Assinar APK
        run: |
          $ANDROID_HOME/build-tools/35.0.0/apksigner sign \
            --ks geotrack-release.jks \
            --ks-key-alias geotrack \
            --ks-pass pass:"${{ secrets.GEOTRACK_KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.GEOTRACK_KEY_PASSWORD }}" \
            --out GeoTrack.apk \
            app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: GeoTrack-APK
          path: GeoTrack.apk
